// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Canonicalizer is an autogenerated mock type for the Canonicalizer type
type Canonicalizer struct {
	mock.Mock
}

// Canonicalize provides a mock function with given fields: s
func (_m *Canonicalizer) Canonicalize(s string) string {
	ret := _m.Called(s)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewCanonicalizer interface {
	mock.TestingT
	Cleanup(func())
}

// NewCanonicalizer creates a new instance of Canonicalizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCanonicalizer(t mockConstructorTestingTNewCanonicalizer) *Canonicalizer {
	mock := &Canonicalizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
