// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CellValuesGetter is an autogenerated mock type for the CellValuesGetter type
type CellValuesGetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: cellIds
func (_m *CellValuesGetter) Execute(cellIds []string) []*string {
	ret := _m.Called(cellIds)

	var r0 []*string
	if rf, ok := ret.Get(0).(func([]string) []*string); ok {
		r0 = rf(cellIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*string)
		}
	}

	return r0
}

type mockConstructorTestingTNewCellValuesGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewCellValuesGetter creates a new instance of CellValuesGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCellValuesGetter(t mockConstructorTestingTNewCellValuesGetter) *CellValuesGetter {
	mock := &CellValuesGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
