// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FindExternalRefsFunc is an autogenerated mock type for the FindExternalRefsFunc type
type FindExternalRefsFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: expression
func (_m *FindExternalRefsFunc) Execute(expression string) []string {
	ret := _m.Called(expression)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(expression)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

type mockConstructorTestingTNewFindExternalRefsFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewFindExternalRefsFunc creates a new instance of FindExternalRefsFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFindExternalRefsFunc(t mockConstructorTestingTNewFindExternalRefsFunc) *FindExternalRefsFunc {
	mock := &FindExternalRefsFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
